# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected', models.IntegerField()),
                ('actual', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Chassis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Code_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_tonnage', models.IntegerField()),
                ('max_lights', models.IntegerField()),
                ('max_mediums', models.IntegerField()),
                ('max_heavies', models.IntegerField()),
                ('max_assaults', models.IntegerField()),
                ('max_clan', models.IntegerField()),
                ('max_inner_sphere', models.IntegerField()),
                ('max_duplicates', models.IntegerField()),
                ('screenshot', models.FileField(upload_to='match_screens/')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mwo_battle_center.Day')),
            ],
        ),
        migrations.CreateModel(
            name='Dropdec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=256)),
                ('drop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mwo_battle_center.Drop')),
            ],
        ),
        migrations.CreateModel(
            name='Dropresult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.IntegerField()),
                ('damage', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dropslot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=256)),
                ('dropdec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mwo_battle_center.Dropdec')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('picture', models.FileField(upload_to='map_screens/')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mwo_battle_center.Code')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_one', models.CharField(max_length=32)),
                ('team_two', models.CharField(max_length=32)),
                ('tournament', models.CharField(max_length=32)),
                ('season', models.IntegerField()),
                ('week', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mwo_battle_center.Chassis')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization_Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('chassis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mwo_battle_center.Chassis')),
            ],
        ),
        migrations.AddField(
            model_name='specialization',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mwo_battle_center.Specialization_Grade'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mwo_battle_center.User'),
        ),
        migrations.AddField(
            model_name='dropslot',
            name='mech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mwo_battle_center.Variant'),
        ),
        migrations.AddField(
            model_name='dropslot',
            name='pilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mwo_battle_center.User'),
        ),
        migrations.AddField(
            model_name='dropslot',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mwo_battle_center.Code'),
        ),
        migrations.AddField(
            model_name='dropresult',
            name='dropslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mwo_battle_center.Dropslot'),
        ),
        migrations.AddField(
            model_name='drop',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mwo_battle_center.Map'),
        ),
        migrations.AddField(
            model_name='day',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mwo_battle_center.Match'),
        ),
        migrations.AddField(
            model_name='code',
            name='code_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mwo_battle_center.Code_Group'),
        ),
        migrations.AddField(
            model_name='chassis',
            name='tech_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mwo_battle_center.Code'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mwo_battle_center.Day'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mwo_battle_center.User'),
        ),
    ]
